
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Algel.WpfIconFonts
{
	using System;
	using System.Windows;
	using System.Windows.Media;

	partial class Internals
	{
		private static readonly Uri BaseUri = new Uri("pack://application:,,,/Algel.WpfIconFonts;component/Resources/");
		private static readonly Typeface[] Typefaces = {
			new Typeface(new FontFamily(BaseUri, "./#Font Awesome 5 Brands"), FontStyles.Normal, FontWeights.Normal, FontStretches.Normal),
			new Typeface(new FontFamily(BaseUri, "./#Font Awesome 5 Free Solid"), FontStyles.Normal, FontWeights.Black, FontStretches.Normal),
			new Typeface(new FontFamily(BaseUri, "./#Font Awesome 5 Free Regular"), FontStyles.Normal, FontWeights.Normal, FontStretches.Normal),
		};
	}
}
